version: "3"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: github_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "adm123"
      PGDATA: /tmp
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
    networks:
      - database-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "postgres@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "adm123"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - database-network

  app:
    build: .
    container_name: github_api_rest
    ports:
      - "5000:5000"
    networks:
      - database-network
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=adm123"
      - "POSTGRES_ADDRESS=postgres"
      - "POSTGRES_DB=github_api"
      - "FLASK_APP=app"
      - "FLASK_ENV=development"
      - "SECRET_KEY=1234443sadfsad3214232qabcsadfsadf"
    depends_on:
      - postgres
      - admin

networks:
  database-network:
    driver: bridge
